### ISSUE TITLE
Deepcopy of pysb.Parameter fails with SymPy 1.9

### ISSUE THREAD

**Issue by dweindl** [pysb/pysb#551]
With the recent [SymPy 1.9](https://github.com/sympy/sympy/wiki/release-notes-for-1.9), `deepcopy` fails for `pysb.Parameter`:

```
import pysb
from copy import deepcopy

pysb.Model()
pysb.Parameter("a", 1)

deepcopy(model)
```
results in `[...] TypeError: __new__() got an unexpected keyword argument 'real'`.

Works with SymPy 1.8.

**Comment by lh64** [comment]
@jmuhlich Any updates on fixing this issue? We ran into this problem recently in my lab when installing PySB on a new student’s computer and we’ve had reports of others with the same problem as well.

**Comment by jmuhlich** [comment]
Yes, @FFroehlich had worked up a fix and we just had to decide whether to retain compatibility with older Sympy and how to retain that in our testing matrix. I just merged the PR as you can see above. I'll make a new release now.
