### PR TITLE
add getnewargs_ex to Symbol, fixes #551

### LINKED ISSUE #551: Deepcopy of pysb.Parameter fails with SymPy 1.9
With the recent [SymPy 1.9](https://github.com/sympy/sympy/wiki/release-notes-for-1.9), `deepcopy` fails for `pysb.Parameter`:

```
import pysb
from copy import deepcopy

pysb.Model()
pysb.Parameter("a", 1)

deepcopy(model)
```
results in `[...] TypeError: __new__() got an unexpected keyword argument 'real'`.

Works with SymPy 1.8.

### PR DESCRIPTION
**Pull request by FFroehlich**
Adds a generic `__getnewargs_ex__` to Symbol class to support deepcopy  via  `__reduce_ex__` (required for sympy 1.9 compatibility). `__getnewargs_ex__` relies on `__getnewargs__` methods implemented in derived model components.

### CODE REVIEW

**Review by jmuhlich — APPROVED** [review]
Thanks, looks good! Our Python 3.6 test runner still uses Sympy 1.8 due to what conda-forge has packaged, so we still have a "free" Sympy 1.8 test for now. Appveyor failed but I think that's an Appveyor problem not a pysb one.
